version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=blogpassword
      - POSTGRES_DB=blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloguser -d blogdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

# To start the database:
# docker-compose up -d
#
# To stop the database:
# docker-compose down
#
# To stop and remove volumes:
# docker-compose down -v
